# Çoklu Lineer Regrasyon

Çoklu doğrusal regrasyan ile çalışan bir veri blimcinin iki hedefimiz olabilir
* bağımzız değişkenlere bakrak bağımlı değişkenin tahmini
* bağımsız değişkenin bağımlı değişkeni nasıl ne derce hangi yönlü etkildediğini bulmak

# Doğrusal Model Varsayımları
* Hatalar normal dağılır
* Hatalar birbirinden bağımsızdır ve aralarında otokorolasyon yoktur
* Her bir gözlem için hata terimleri varyansları sabittir
* Değişkenler ile hata terimi arasında ilişki yoktur
* Bağımsız değişkenler arasında çoklu doğrusal ilişki problemi yoktur

hocam bu varsayımlar akedemide çok çok önemlidir ancak sektörde it works than don't tuch it mantığında kayda alınmazlar


# Regresyon Modellerinin Avantajları
* Doğrusallık nedensellik yorumları yapılabilmesini sağlar, bu durum Aksiyoner ve stratejik modelleme imkanı verir
* Değişkenlerin etki düzeyleri ve anlamlılıkları değrlendirilebilir
* Bağımlı değişkendeki değişkenliğin açıklanma başarısı ölçülebilir
* model anlamlığı değerledirilebilir

# Regresyon Modelleri Dezavantajları
* Varsayımları vardır
* Aykırı gözlemlere duyalıdır

özellikle çoklu doğrusal bağlantı problemini sevmeyiz

In [115]:
import pandas as pd
ad=pd.read_csv("Advertising.csv",usecols=[1,2,3,4])#biliyorsun bu kısmı indexleri değişken gibi gördi bunu düzeltmek için yaptık
df=ad.copy()
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [116]:
df.shape

(200, 4)

In [117]:
#X diye bir değişkenen tüm bağımsız değişkenleri topluyoruz
#anladın işte aslında bağımlı değişkenş siliyorız 
X=df.drop("sales",axis=1)
X[0:5]

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [118]:
# Y diye bir değişkene de bağınmlık değişkenş atıyoruz
Y=df["sales"] 
Y[0:5]

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [119]:
#sırasıyla ayırım,score hesaplama ve tahmin için fonksiyonları aldık
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict

In [120]:
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.20, random_state=144) 

In [121]:
X_train.shape

(160, 3)

In [122]:
X_test.shape

(40, 3)

In [123]:
Y_train.shape

(160,)

In [124]:
Y_test.shape

(40,)

In [125]:
#görüldüğü üzere veri seti 80 e 20 gözlem olarak ayrılmış
# train ve test olarak 160 a 40 olarak bölünmüş
#lazım olabilir diye veri setinin ilk halini saklıyoruz
traning=df.copy

# Stats Model
hocam eğer yorum yapayım dersen statsmodel kullanılır ama bunlara girmeyeceğim dersen sklearn kullanılır ki daha çok bunun kullanacağız

In [126]:
import statsmodels.api as sm
lm=sm.OLS(Y_train, X_train)
model=lm.fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.981
Method:                 Least Squares   F-statistic:                              2787.
Date:                Wed, 08 Feb 2023   Prob (F-statistic):                   7.04e-136
Time:                        21:13:52   Log-Likelihood:                         -339.00
No. Observations:                 160   AIC:                                      684.0
Df Residuals:                     157   BIC:                                      693.2
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0544      0.002     36.212      0.000       0.051       0.057
radio          0.2127      0.011     18.979      0.000       0.191       0.235
newspaper      0.0230      0.008      2.887      0.004       0.007       0.039
==============================================================================
Omnibus:                        6.947   Durbin-Watson:                   1.857
Prob(Omnibus):                  0.031   Jarque-Bera (JB):                7.358
Skew:                          -0.359   Prob(JB):                       0.0253
Kurtosis:                       3.766   Cond. No.                         13.4
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [127]:
# hocam bu  P>|t| değerlerine bakarak bağımsız değişlüknelerin anlamlılığını kontrol ediyoruz.
# bu modelde hepsi anlamlı
# başka bir model kuracak dahi olsan lineer modeli kurup değişken anlamlılığını kontrol etmekte fayda var

In [128]:
# katsayı (coef) muhabbetini de biliyorsun verilen değişkendeki bir bieim artış bağımlı değişkenş ne kadar etkiliyor ona bakcağız

In [129]:
model.summary().tables[1]

<class 'statsmodels.iolib.table.SimpleTable'>

### Nedir Bu R-squared f_statistic değerleri
R_squared ve adj.R_squared değerleri bağımlı değişkendeki değişikliğin bağımsız değişkenlerle açıklanabilirliğini belirtir. varyans açılama başarıs yani

F_statistic ise modelşn anlamlılıpını değerlendirir


-> modellerin tahmin başarısını değerlendirmemk için mse rmse 'ye bakılır 

# Sckit Learn

In [130]:
from sklearn.linear_model import LinearRegression

In [131]:
lm=LinearRegression()
model=lm.fit(X_train, Y_train)

In [132]:
#sabit katsayı
model.intercept_

2.9470477340696704

In [133]:
#tüm bağımsız değişkenlerşn kat sayıları
model.coef_

array([0.04654781, 0.18148351, 0.00077954])

# Tahmin
model Denklemi:

salaes = 2.97 + 0.04TV + 0.18radio + 0.002newsPapper

Örneğin 30 birim Tv harcaması, 10 birim radyo harcaması, 40 birim gazete harcaması olsupund asatısşalrın tahmini deeğri ne olur?

In [134]:
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score

In [135]:
yeni_veri=[[30],[10],[40]]
yeni_veri=pd.DataFrame(yeni_veri).T


In [136]:
model.predict(yeni_veri)
#tahmini, yaptık sonuc: 6.32

/Users/necmiyesoyla/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6.18949881])

In [137]:
#eğitim hatası
rmse=np.sqrt(mean_squared_error(Y_train,model.predict(X_train)))#paremetre olarak gerçek y değerleri sonra tahmin edilen y değerleri verildi-train'deki-
rmse

1.6748559274650712

In [138]:
#test hatası
#hocam yaptığımız şu önce modelde kullandığımız datalar üzerinden eğitim hatasına baktık. sonra aynı fonksiyona 
# modelin görmediği test için ayrılan y değerleni ve
# modelede yine tahmin için modelin görmediği x değerlerini verdik ki yeni tahmin yapsın sonrada işte rmse değerine baktık
rmse=np.sqrt(mean_squared_error(Y_test,model.predict(X_test)))
rmse

1.6640263686701038

# Model Tuning / Model Doğrulama
şimdi yukarıda split işlemini yaparken random_state=42 dedik işte eğer bu değeri değiştirisek eşde ettiğimiz smse değeri de değişir 

Peki beu değeri kaç yapmalıyız işte optimim değeri hseplamak için cross value hesaplıyoruz



In [139]:
cross_val_score(model, X, Y, cv=10, scoring="r2")
#burada on adet cross value eld ettik

array([0.87302696, 0.8581613 , 0.92968723, 0.89013272, 0.93146498,
       0.93138735, 0.7597901 , 0.91217097, 0.83891753, 0.92882311])

In [140]:
#ortalamasını alıyoruz. 
#işte bizim modelimizin valide edilmiş doğrulanmış r2 değeri budur
cross_val_score(model, X, Y, cv=10, scoring="r2").mean()

#şu an bunu tüm veri seti için yaptık şimdi sadece train için yapalım

0.8853562237979616

In [141]:
cross_val_score(model,X_train, Y_train, cv=10, scoring="r2").mean()


0.873378329842294

In [142]:
-cross_val_score(model,X_train, Y_train, cv=10, scoring="neg_mean_squared_error").mean()


3.0491814361587064

In [148]:
np.sqrt(-cross_val_score(model,X_train, Y_train, cv=10, scoring="neg_mean_squared_error")).mean()

1.6649345607872932

In [144]:
-cross_val_score(model,X_test, Y_test, cv=10, scoring="neg_mean_squared_error").mean()


3.31745515304909

In [146]:
np.sqrt(-cross_val_score(model,X_test, Y_test, cv=10, scoring="neg_mean_squared_error")).mean()

1.7399924960346655